### ISSUE TITLE
Dashboard is broken - Unable to connect to SSL

### ISSUE THREAD

**Issue by creativecat** [BlackCatDevelopment/BlackCatCMS#360] opened 2016-11-19 15:47 UTC
As we changed our URL to http**s** the widgets for version check and forum news are not able to connect to http any more.

**Comment by creativecat** [comment] 2016-11-19 15:58
Seems to be this issue https://github.com/zendframework/zendframework/pull/5870

**Comment by creativecat** [comment] 2016-11-19 16:23
I modified the .htaccess on our server to enable the version file over standard http - should work but there should be a solution to enable the access over https as well.

**Comment by webbird** [comment] 2016-11-21 15:09
I made a new version of check.php (version check widget) to use GitHub instead of version.txt. As for the forum, you can add

'sslverifypeer' => false

though it's not "as intended by the inventor".

**Comment by webbird** [comment] 2016-12-29 09:47
Fixed by replacing Zend with CUrl.

**Closed by webbird** 2016-12-29 09:47 UTC
Labels: bug, in progress, to be tested
