### ISSUE TITLE
Problematic characters in DB Password

### ISSUE THREAD

**Issue by creativecat** [BlackCatDevelopment/BlackCatCMS#355] opened 2016-08-09 18:28 UTC
In some cases installation will fail because of some special characters (e.g. ! ) in a database password. There might be a problem with parsing the .ini?

**Comment by webbird** [comment] 2016-08-15 16:29
Testet on Windows, works for me...

**Comment by creativecat** [comment] 2016-11-10 09:02
I could check in my database for those characters:
/-_#*+!§,()=:.@äöüÄÖÜß

Problematic characters are: §äöüÄÖÜß
Using those characters the installation process can not connect to the database.

Successfully tested characters during the installation are /-_#*+!,()=:.@

But after installation the parse_ini-file() throw an error:
"Warning: syntax error, unexpected '(' in..."
=> This was caused again by the index.php as $file included the whole path but not only "index.php"... I gonna fix this.

But as I read on [php.net](http://de2.php.net/manual/en/function.parse-ini-file.php#refsect1-function.parse-ini-file-notes) those values are not allowed in a file: **?{}|&~!()^"** 
Nevertheless /-_#*+!,()=:.@ is working fine in my installations also there is e.g. ) or ! in the password.

**Comment by webbird** [comment] 2016-11-21 15:27
So we have a problem caused by the fact I decided to store the DB credentials in an INI file? Could this issue be fixed by using a PHP (like config.php)?

**Comment by creativecat** [comment] 2016-11-25 08:08
I'm going to test this....

**Comment by webbird** [comment] 2016-11-25 09:38
For v1.x I added a note to our homepage.

https://blackcat-cms.org/page/download/bekannte-probleme.php

For v2.x we can try to find a solution.

**Closed** 2016-11-25 09:39 UTC
Labels: bug, to be tested
